name: F1-sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: sync-TV-BOX-Script

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # === 获取 GitHub 最新 commit ===
      - name: Get GitHub latest commit
        id: github_latest
        run: |
          rm -rf temp-github || true
          if git clone --depth 1 --filter=blob:none --sparse https://github.com/yuanwangokk-1/TV-BOX temp-github; then
            cd temp-github
            git sparse-checkout set tvbox/pro
            GH_COMMIT=$(git rev-parse HEAD)
            echo "GH_COMMIT=$GH_COMMIT" >> $GITHUB_OUTPUT
            cd ..
            rm -rf temp-github
          else
            echo "⚠️ GitHub 仓库克隆失败，跳过 GitHub 同步"
            echo "GH_COMMIT=N/A" >> $GITHUB_OUTPUT
          fi

      # === 获取 Gitee 最新 commit ===
      - name: Get Gitee latest commit
        id: gitee_latest
        run: |
          rm -rf temp-gitee || true
          if git clone --depth 1 https://gitee.com/PizazzXS/another-d.git temp-gitee; then
            cd temp-gitee
            GITEE_COMMIT=$(git rev-parse HEAD)
            echo "GITEE_COMMIT=$GITEE_COMMIT" >> $GITHUB_OUTPUT
            cd ..
            rm -rf temp-gitee
          else
            echo "⚠️ Gitee 仓库克隆失败，跳过 Gitee 同步"
            echo "GITEE_COMMIT=N/A" >> $GITHUB_OUTPUT
          fi

      # === 判断是否需要同步 ===
      - name: Check if sync is needed
        id: check_sync
        run: |
          LAST_SYNC_FILE=".last_sync"
          LAST_GH_COMMIT=$(cut -d' ' -f1 $LAST_SYNC_FILE 2>/dev/null || echo "none")
          LAST_GITEE_COMMIT=$(cut -d' ' -f2 $LAST_SYNC_FILE 2>/dev/null || echo "none")

          SYNC_GH=false
          SYNC_GITEE=false

          if [ "${{ steps.github_latest.outputs.GH_COMMIT }}" != "N/A" ] && [ "$LAST_GH_COMMIT" != "${{ steps.github_latest.outputs.GH_COMMIT }}" ]; then
            SYNC_GH=true
          fi

          if [ "${{ steps.gitee_latest.outputs.GITEE_COMMIT }}" != "N/A" ] && [ "$LAST_GITEE_COMMIT" != "${{ steps.gitee_latest.outputs.GITEE_COMMIT }}" ]; then
            SYNC_GITEE=true
          fi

          echo "sync_github=$SYNC_GH" >> $GITHUB_OUTPUT
          echo "sync_gitee=$SYNC_GITEE" >> $GITHUB_OUTPUT

      # === 同步 GitHub 到 TV-BOX 分支（仅有更新时） ===
      - name: Sync GitHub to TV-BOX
        if: steps.check_sync.outputs.sync_github == 'true'
        run: |
          echo "=== 同步 GitHub 到 TV-BOX 分支 ==="
          rm -rf upstream-github merged-github || true
          git clone --depth 1 --filter=blob:none --sparse https://github.com/yuanwangokk-1/TV-BOX upstream-github
          cd upstream-github
          git sparse-checkout set tvbox/pro
          mkdir ../merged-github
          cp -r tvbox/pro ../merged-github/tvbox_pro_github
          cd ../merged-github
          git init
          git checkout -B TV-BOX
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync GitHub(tvbox/pro:${{ steps.github_latest.outputs.GH_COMMIT }}) at $(date '+%Y-%m-%d %H:%M:%S')"
          git remote add dest https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push --force dest TV-BOX

      # === 同步 Gitee 到 潇洒 分支（仅有更新时） ===
      - name: Sync Gitee to 潇洒
        if: steps.check_sync.outputs.sync_gitee == 'true'
        run: |
          echo "=== 同步 Gitee 到 潇洒 分支 ==="
          rm -rf upstream-gitee merged-gitee || true
          git clone --depth 1 https://gitee.com/PizazzXS/another-d.git upstream-gitee
          mkdir merged-gitee
          cp -r upstream-gitee merged-gitee/another-d
          cd merged-gitee
          git init
          git checkout -B 潇洒
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 更新 CHANGELOG.md，最新记录置顶
          CHANGELOG_FILE="CHANGELOG.md"
          NEW_ENTRY="* Sync Gitee(another-d:${{ steps.gitee_latest.outputs.GITEE_COMMIT }}) at $(date '+%Y-%m-%d %H:%M:%S')"
          if [ -f "$CHANGELOG_FILE" ]; then
            echo -e "$NEW_ENTRY\n$(cat $CHANGELOG_FILE)" > $CHANGELOG_FILE
          else
            echo "$NEW_ENTRY" > $CHANGELOG_FILE
          fi

          git add .
          git commit -m "Sync Gitee(another-d:${{ steps.gitee_latest.outputs.GITEE_COMMIT }}) at $(date '+%Y-%m-%d %H:%M:%S')"
          git remote add dest https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git push --force dest 潇洒

      # === 更新本次同步 commit ===
      - name: Update last sync record
        if: steps.check_sync.outputs.sync_github == 'true' || steps.check_sync.outputs.sync_gitee == 'true'
        run: |
          echo "${{ steps.github_latest.outputs
