## 每隔3小时拉取一次作者脚本到自己仓库的分支
name: F1-sync

on:
  schedule:
    - cron: '6 */3 * * *'   # 每隔3小时执行一次
  workflow_dispatch:         # 手动触发
  watch:
    types: started           # 关注触发
  repository_dispatch:
    types: sync-TV-BOX-Script

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone only tvbox/pro from upstream
        run: |
          echo "=== 开始克隆上游仓库 ==="
          git clone --depth 1 --filter=blob:none --sparse https://github.com/yuanwangokk-1/TV-BOX upstream
          cd upstream
          git sparse-checkout set tvbox/pro
          echo "=== 上游 tvbox/pro 克隆完成 ==="
          ls -R tvbox/pro

      - name: Push tvbox/pro to my repo TV-BOX branch
        run: |
          echo "=== 开始准备推送到目标仓库 ==="
          cd upstream
          mkdir repo
          mv tvbox/pro repo/
          cd repo

          git init
          git checkout -b TV-BOX
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Sync tvbox/pro from upstream at $(date '+%Y-%m-%d %H:%M:%S')"

          echo "=== 推送到 ${GITHUB_REPOSITORY} 的 TV-BOX 分支 ==="
          git remote add dest https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}

          if git push --force dest TV-BOX; then
            echo "✅ 同步成功！"
          else
            echo "❌ 同步失败，请检查 PAT 权限或仓库设置"
            exit 1
          fi



